language: php

git:
  depth: 3
  submodules: false

matrix:
  fast_finish: true

php:
  - 5.6
  - 7.0

before_script:
  - composer install

script: phpunit --coverage-text

notifications: 
  email: false
  webhooks: https://coveralls.io/webhook?repo_token=$CA_TOKEN

env:
  global:
    secure: "JzW5SFPLi1ZAFPtj6p0Hq8Mwr7hi79x3KHjLJk2dSSBsAfE7VdLwYU0EEK/gx6K0x9GTeIf516fo/fIeO5cihQ+QfiGOzv1QG+q6tdbBi2TQwQfReRMNUFayw7rl7YtC0p9p8E8nUT6naI7ljXV1AS+qs17Sl2Be5ujAB33VqilwlyxvmcDCok49DlGmT82d2Shx0JHM+cdGD0/Z9fDkRyKX/51LSNV0CZjzkiBRhOlACAhqpt8/S35+sjXHBmtZcFzv4W0zDNPA3llwYs3DX8HHQzRfTQOdYDBpTvs549BUnHivaH2tbWMH7lRCbCZWh9EA84kLwhhsCoooFWCfq+FXYJnI8QRRq1Cm3pTURSHYQZ0aLZ/lxMcgjI0bXl5lpZbSVQY4qxoiLcb2cRgUYubdl1bqGiiBd1yC58nRDVmDgKC4xIvSibFbLJzxH0OCjwzlyLAcTVW6Tbe8EaytuNz/BDZRJV8VgGC4NrGahvBWnIE9Qzar7GH4A8IhPtXS82voiPN1yRe68nmYLLNKmub2iGlvKy/a3oT/zg/0da9OAEPWCmv2Zf7wcm37fp43UcN3lCmDHVSXhZKe86R1cIU4ueM9hxRRXXFPj+01lrnIt+JfcrDqnmhrU0q0jxla1kDj1U55upG1Fs1OcIqTN+m3MD06F9XAIqDhiITNGB4="
