language: php

git:
  depth: 3
  submodules: false

matrix:
  fast_finish: true

php:
  - 5.6
  - 7.0

before_script:
  - composer install

script: phpunit --coverage-text

notifications: 
  email: false
